services:
  mkdocs:
    image: squidfunk/mkdocs-material
    command:
      - build
    volumes:
      - ./mkdocs:/docs

  traefik:
    image: traefik:latest
    command:
      - --configFile=/etc/traefik/traefik.yml
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/etc:/etc/traefik:ro
      - ./traefik/log:/var/log/traefik
      - ./traefik/tls:/letsencrypt

  nginx:
    image: nginx:latest
    labels:
      - traefik.enable=true
      - traefik.http.routers.rskio.entrypoints=websecure
      - traefik.http.routers.rskio.rule=Host(`rskio.com`)
      - traefik.http.routers.rskio.tls=true
      - traefik.http.routers.rskio.tls.certresolver=rskio_certresolver
      - traefik.http.routers.rskio.service=rskio@docker
      - traefik.http.services.rskio.loadbalancer.server.port=80
    volumes:
      - ./mkdocs/site:/opt/share/mkdocs/html:ro
      - ./nginx/etc/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      mkdocs:
        condition: service_completed_successfully

