services:
  traefik:
    image: traefik:latest
    command:
      - --configFile=/etc/traefik/traefik.yml
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/etc:/etc/traefik:ro
      - ./traefik/log:/var/log/traefik
      - ./traefik/tls:/letsencrypt

  mkdocs:
    image: squidfunk/mkdocs-material
    labels:
      - traefik.enable=true
      - traefik.http.routers.rskio.entrypoints=websecure
      - traefik.http.routers.rskio.rule=Host(`rskio.com`)
      - traefik.http.routers.rskio.tls=true
      - traefik.http.routers.rskio.tls.certresolver=rskio_certresolver
      - traefik.http.routers.rskio.service=rskio@docker
      - traefik.http.services.rskio.loadbalancer.server.port=8000
    volumes:
      - ./mkdocs:/docs

