global:
  checkNewVersion: false
  sendAnonymousUsage: false

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          priority: 10
  websecure:
    address: :443
    http3:
      advertisedPort: 443

certificatesresolvers:
  rskio_certresolver:
    acme:
      tlschallenge: true
      email: rskntroot@gmail.com
      storage: /letsencrypt/acme.json

log:
  level: INFO
  format: json
  filePath: /var/log/traefik/traefik.log

accessLog:
  format: json
  filePath: /var/log/traefik/access.log

api:
  insecure: true
#  dashboard: false

providers:
  docker:
    endpoint: unix:///var/run/docker.sock
    network: rskio_default
    exposedByDefault: false
#  file:
#    filename: /etc/traefik/dynamic.yml
#    watch: true

