site_name: Rskio
site_url: https://rskio.com/
repo_name: rskntroot/rskio
repo_url: https://github.com/rskntroot/rskio
theme:
  name: material
  features:
    - navigation.instant
    - content.code.copy
    - content.code.select
  icon:
    admonition:
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
    annotation: material/plus-circle
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
watch:
  - includes
